export const heroesStrengthList = [
  "Alchemist",
  "Axe",
  "Bristleback",
  "Centaur Warrunner",
  "Chaos Knight",
  "Dawnbreaker",
  "Doom",
  "Dragon Knight",
  "Earth Spirit",
  "Earthshaker",
  "Elder Titan",
  "Huskar",
  "Kunkka",
  "Legion Commander",
  "Lifestealer",
  "Mars",
  "Night Stalker",
  "Ogre Magi",
  "Omniknight",
  "Primal Beast",
  "Pudge",
  "Slardar",
  "Spirit Breaker",
  "Sven",
  "Tidehunter",
  "Tiny",
  "Treant Protector",
  "Tusk",
  "Underlord",
  "Undying",
  "Wraith King",
];

export const heroesAgilityList = [
  "Anti-Mage",
  "Arc Warden",
  "Bloodseeker",
  "Bounty Hunter",
  "Clinkz",
  "Drow Ranger",
  "Ember Spirit",
  "Faceless Void",
  "Gyrocopter",
  "Hoodwink",
  "Juggernaut",
  "Luna",
  "Medusa",
  "Meepo",
  "Monkey King",
  "Morphling",
  "Naga Siren",
  "Phantom Assassin",
  "Phantom Lancer",
  "Razor",
  "Riki",
  "Shadow Fiend",
  "Slark",
  "Sniper",
  "Spectre",
  "Templar Assassin",
  "Terrorblade",
  "Troll Warlord",
  "Ursa",
  "Viper",
  "Weaver",
];

export const heroesIntelligenceList = [
  "Ancient Apparition",
  "Crystal Maiden",
  "Death Prophet",
  "Disruptor",
  "Enchantress",
  "Grimstroke",
  "Jakiro",
  "Keeper of the Light",
  "Leshrac",
  "Lich",
  "Lina",
  "Lion",
  "Muerta",
  "Natures Prophet",
  "Necrophos",
  "Oracle",
  "Outworld Destroyer",
  "Puck",
  "Pugna",
  "Queen of Pain",
  "Rubick",
  "Shadow Demon",
  "Shadow Shaman",
  "Silencer",
  "Skywrath Mage",
  "Storm Spirit",
  "Tinker",
  "Warlock",
  "Witch Doctor",
  "Zeus",
];

export const heroesUniversalList = [
  "Abaddon",
  "Bane",
  "Batrider",
  "Beastmaster",
  "Brewmaster",
  "Broodmother",
  "Chen",
  "Clockwerk",
  "Dark Seer",
  "Dark Willow",
  "Dazzle",
  "Disruptor",
  "Enigma",
  "Invoker",
  "Io",
  "Lone Druid",
  "Lycan",
  "Magnus",
  "Mirana",
  "Nyx Assassin",
  "Pangolier",
  "Phoenix",
  "Pudge",
  "Riki",
  "Sand King",
  "Snapfire",
  "Techies",
  "Timbersaw",
  "Windranger",
  "Winter Wyvern",
  "Void Spirit",
  "Vengeful Spirit",
  "Venomancer",
  "Visage",
];
export const heroList = [
  "Abaddon",
  "Alchemist",
  "Ancient Apparition",
  "Anti-Mage",
  "Arc Warden",
  "Axe",
  "Bane",
  "Batrider",
  "Beastmaster",
  "Bloodseeker",
  "Bounty Hunter",
  "Brewmaster",
  "Bristleback",
  "Broodmother",
  "Centaur Warrunner",
  "Chaos Knight",
  "Chen",
  "Clinkz",
  "Clockwerk",
  "Crystal Maiden",
  "Dark Seer",
  "Dark Willow",
  "Dawnbreaker",
  "Dazzle",
  "Death Prophet",
  "Disruptor",
  "Doom",
  "Dragon Knight",
  "Drow Ranger",
  "Earth Spirit",
  "Earthshaker",
  "Elder Titan",
  "Ember Spirit",
  "Enchantress",
  "Enigma",
  "Faceless Void",
  "Grimstroke",
  "Gyrocopter",
  "Hoodwink",
  "Huskar",
  "Invoker",
  "Io",
  "Jakiro",
  "Juggernaut",
  "Keeper of the Light",
  "Kunkka",
  "Legion Commander",
  "Leshrac",
  "Lich",
  "Lifestealer",
  "Lina",
  "Lion",
  "Lone Druid",
  "Luna",
  "Lycan",
  "Magnus",
  "Mars",
  "Medusa",
  "Meepo",
  "Mirana",
  "Monkey King",
  "Morphling",
  "Muerta",
  "Naga Siren",
  "Natures Prophet",
  "Necrophos",
  "Night Stalker",
  "Nyx Assassin",
  "Ogre Magi",
  "Omniknight",
  "Oracle",
  "Outworld Destroyer",
  "Pangolier",
  "Primal Beast",
  "Phantom Assassin",
  "Phantom Lancer",
  "Phoenix",
  "Puck",
  "Pudge",
  "Pugna",
  "Queen of Pain",
  "Razor",
  "Riki",
  "Rubick",
  "Sand King",
  "Shadow Demon",
  "Shadow Fiend",
  "Shadow Shaman",
  "Silencer",
  "Skywrath Mage",
  "Slardar",
  "Slark",
  "Snapfire",
  "Sniper",
  "Spectre",
  "Spirit Breaker",
  "Storm Spirit",
  "Sven",
  "Techies",
  "Templar Assassin",
  "Terrorblade",
  "Tidehunter",
  "Timbersaw",
  "Tinker",
  "Tiny",
  "Treant Protector",
  "Troll Warlord",
  "Tusk",
  "Underlord",
  "Undying",
  "Ursa",
  "Vengeful Spirit",
  "Venomancer",
  "Viper",
  "Visage",
  "Void Spirit",
  "Warlock",
  "Weaver",
  "Windranger",
  "Winter Wyvern",
  "Witch Doctor",
  "Wraith King",
  "Zeus",
];
